---
- name: Set up RHEL
  hosts: all
  tasks:
    - name: Subscribe container
      redhat_subscription:
        auto_attach: true
        force_register: true
        password: "{{ lookup('env','REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD') }}"
        username: "{{ lookup('env','REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME') }}"
    - name: Install EPEL
      package:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
    - name: Create test user
      user:
        name: test
